# Generated by Django 6.1.1 on 2026-09-21 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام دسته\u200cبندی"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="آدرس اینترنتی (Slug)"
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام ساعت")),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="آدرس اینترنتی (Slug)"
                    ),
                ),
                ("brand", models.CharField(max_length=100, verbose_name="برند")),
                ("description", models.TextField(verbose_name="توضیحات ساعت")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="قیمت (تومان)"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/%Y/%m/", verbose_name="تصویر ساعت"
                    ),
                ),
                ("stock", models.PositiveIntegerField(verbose_name="موجودی در انبار")),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="نمایش در سایت"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="shop.category",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "ساعت",
                "verbose_name_plural": "ساعت\u200cها",
                "ordering": ("-created",),
            },
        ),
    ]
