# Generated by Django 6.1.1 on 2026-09-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                related_name="products",
                to="shop.category",
                verbose_name="دسته\u200cبندی\u200cها",
            ),
        ),
    ]
